import { NextFunction, Request, Response } from "express";
import Account from "$models/Account.model";
import AppError from "$root/utils/AppError.util";
import { RoleEnum } from "$root/enums/RoleEnum";
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");

const JWT_SECRET = process.env.JWT_SECRET || "your-secret-key";

interface AuthenticatedRequest extends Request {
  user?: { _id: string; role: string };
}

/**
 * @swagger
 * components:
 *   schemas:
 *     Account:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           description: The unique identifier for the account (auto-generated by MongoDB)
 *           readOnly: true
 *         username:
 *           type: string
 *           description: The username of the account
 *         password:
 *           type: string
 *           description: The password of the account (hashed in database)
 *         email:
 *           type: string
 *           format: email
 *           description: The email address of the account
 *         role:
 *           type: string
 *           description: The role of the user (e.g., admin, user, etc.)
 *         dob:
 *           type: string
 *           format: date
 *           nullable: true
 *           description: The date of birth of the account holder
 *       required:
 *         - username
 *         - password
 *         - email
 *         - role
 */

// Get all accounts
/**
 * @swagger
 * /api/account:
 *   get:
 *     summary: Retrieve a list of all accounts
 *     tags:
 *       - Accounts
 *     responses:
 *       200:
 *         description: A list of accounts
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Account'
 *       404:
 *         description: No accounts found
 *       500:
 *         description: Server error
 */
const getAllAccounts = async (
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {

  if (!req.user) {
    return next(new AppError("Authentication required", 401));
  }
  if (req.user.role !== RoleEnum.Admin) {
    return next(new AppError("Unauthorized: Admin access required", 403));
  }
  try {
    const users = await Account.find();
    if (!users || users.length === 0) {
      return next(new AppError("No accounts found", 404));
    }
    res.status(200).json(users);
  } catch (err: AppError | any) {
    return next(new AppError("Internal Server Error", 500));
  }
};

// Get one account
/**
 * @swagger
 * /api/account/{id}:
 *   get:
 *     summary: Retrieve a single account by ID
 *     tags:
 *       - Accounts
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The account ID
 *     responses:
 *       200:
 *         description: A single account
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Account'
 *       404:
 *         description: Account not found
 *       500:
 *         description: Server error
 */
const getAccount = async (
  req: AuthenticatedRequest & { params: { id: string } }, // Combine types
  res: Response,
  next: NextFunction
): Promise<void> => {
  if (!req.user) {
    return next(new AppError("Authentication required", 401));
  }
  try {
    const { id } = req.params;
    if (!id) {
      return next(new AppError("Account ID is required", 400));
    }

    const user = await Account.findById(id);
    if (!user) {
      return next(new AppError("Account not found", 404));
    }

    res.status(200).json({
      message: "Account retrieved successfully",
      user,
    });
  } catch (error) {
    console.error("Get account error:", error instanceof Error ? error.stack : error);
    return next(new AppError("Internal Server Error", 500));
  }
};
// Create one account
/**
 * @swagger
 * /api/account:
 *   post:
 *     summary: Create a new account
 *     tags:
 *       - Accounts
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Account'
 *     responses:
 *       201:
 *         description: The created account
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Account'
 *       400:
 *         description: Bad request
 *       500:
 *         description: Server error
 */
const createAccount = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    if (
      !req.body.username ||
      !req.body.password ||
      !req.body.email ||
      !req.body.dob
    ) {
      return next(new AppError("Bad request", 400));
    }

    const user = new Account({
      username: req.body.username,
      password: req.body.password,
      email: req.body.email,
      role: req.body.role,
      dob: req.body.dob,
      isActive: true,
    });

    const newUser = await user.save();
    res.status(200).json(newUser);
  } catch (err: Error | any) {
    return next(new AppError("Internal Server Error", 500));
  }
};

// Delete one account
/**
 * @swagger
 * /api/account/{id}:
 *   delete:
 *     summary: Delete an account by ID
 *     description: This endpoint allows the deletion of an account based on its ID. Returns the deleted account if successful.
 *     tags:
 *       - Accounts
 *     parameters:
 *       - name: id
 *         in: path
 *         description: ID of the account to delete
 *         required: true
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Account deleted successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 _id:
 *                   type: string
 *                 message:
 *                   type: string
 *       404:
 *         description: Account not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 */
const deleteAccount = async (
  req: AuthenticatedRequest & { params: { id: string } },
  res: Response,
  next: NextFunction
): Promise<void> => {
  if (!req.user) {
    return next(new AppError("Authentication required", 401));
  }
  if (req.user.role !== RoleEnum.Admin) {
    return next(new AppError("Unauthorized: Admin access required", 403));
  }

  try {
    const { id } = req.params;
    if (!id) {
      return next(new AppError("Account ID is required", 400));
    }

    const user = await Account.findByIdAndDelete(id);
    if (!user) {
      return next(new AppError("Account not found", 404));
    }

    res.status(200).json({
      message: "Account deleted successfully",
      _id: user._id,
    });
  } catch (error) {
    console.error("Delete account error:", error instanceof Error ? error.stack : error);
    return next(new AppError("Internal Server Error", 500));
  }
};

// Update one account
/**
 * @swagger
 * /api/account/{id}:
 *   put:
 *     summary: Update an account by ID
 *     description: This endpoint allows the updating of an account based on its ID. Returns the updated account if successful.
 *     tags:
 *       - Accounts
 *     parameters:
 *       - name: id
 *         in: path
 *         description: ID of the account to update
 *         required: true
 *         schema:
 *           type: string
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Account'
 *     responses:
 *       200:
 *         description: Account after updated
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Account'
 *       404:
 *         description: Account not found
 *       500:
 *         description: Server error
 */
interface UpdateAccountBody {
  username?: string;
  email?: string;
  role?: string;
  dob?: string;
}

const updateAccount = async (
  req: AuthenticatedRequest & { params: { id: string }; body: UpdateAccountBody },
  res: Response,
  next: NextFunction
): Promise<void> => {
  if (!req.user) {
    return next(new AppError("Authentication required", 401));
  }

  try {
    const { id } = req.params;
    if (!id) {
      return next(new AppError("Account ID is required", 400));
    }

    const updates = req.body;
    if (Object.keys(updates).length === 0) {
      return next(new AppError("No update data provided", 400));
    }

    const user = await Account.findByIdAndUpdate(
      id,
      updates,
      { new: true, runValidators: true } 
    );
    if (!user) {
      return next(new AppError("Account not found", 404));
    }

    res.status(200).json({
      message: "Account updated successfully",
      user,
    });
  } catch (error) {
    console.error("Update account error:", error instanceof Error ? error.stack : error);
    return next(new AppError("Internal Server Error", 500));
  }
};



const register = async (req: Request, res: Response, next: NextFunction) => {
  const { username, email, password, dob } = req.body;
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const errors: { msg: string }[] = [];

  // Input validation
  if (!username || !email || !password || !dob) {
    errors.push({ msg: "Please enter all required fields (username, email, password, date of birth)" });
  }
  if (password && password.length < 6) {
    errors.push({ msg: "Password must be at least 6 characters" });
  }
  if (errors.length > 0) {
    res.status(400).json({ errors });
    return;
  }

  // Convert and validate dob
  const dobDate = new Date(dob);
  if (isNaN(dobDate.getTime())) {
    errors.push({ msg: "Invalid date of birth format. Use YYYY-MM-DD." });
    res.status(400).json({ errors });
    return;
  }

  const dobYear = dobDate.getFullYear();
  if (dobYear > currentYear) {
    errors.push({ msg: "Date of Birth cannot be in the future" });
    res.status(400).json({ errors });
    return;
  }
  if (dobYear < currentYear - 120) {
    errors.push({ msg: "Date of Birth cannot be more than 120 years in the past" });
    res.status(400).json({ errors });
    return;
  }

  try {
    // Check for existing email or username
    const existingEmail = await Account.findOne({ email });
    if (existingEmail) {
      errors.push({ msg: "Email already exists" });
      res.status(400).json({ errors });
      return;
    }

    const existingUsername = await Account.findOne({ username });
    if (existingUsername) {
      errors.push({ msg: "Username already exists" });
      res.status(400).json({ errors });
      return;
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Create new user with dob as Date object
    const newUser = new Account({
      username,
      email,
      password: hashedPassword,
      role: RoleEnum.Customer,
      dob: dobDate, 
      isActive: true,
    });

    await newUser.save();
    console.log("User registered successfully:", newUser);

    res.status(201).json({
      message: "Registration successful, please log in",
    });
  } catch (error) {
    console.error("Registration error:", error instanceof Error ? error.stack : error);
    res.status(500).json({ errors: [{ msg: "Server error occurred. Please try again." }] });
  }
};



const login = async (req: Request, res: Response, next: NextFunction) => {
  const { email, password } = req.body as { email?: string; password?: string };
  const errors: { msg: string }[] = [];

  if (!email || !password) {
    errors.push({ msg: "Email and password are required" });
    res.status(400).json({ errors });
    return;
  }

  try {
    const user = await Account.findOne({ email });
    if (!user || !(await bcrypt.compare(password, user.password))) {
      errors.push({ msg: "Invalid credentials" });
      res.status(401).json({ errors });
      return;
    }

    const token = jwt.sign(
      { _id: user._id, role: user.role },
      JWT_SECRET,
      { expiresIn: "1d" }
    );

    res.cookie("jwt", token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict" as const,
      maxAge: 24 * 60 * 60 * 1000,
    });

    console.log("User logged in:", user.email);
    res.status(200).json({
      message: "Login successful",
      user: {
        username: user.username,
        email: user.email,
        dob: user.dob,
        role: user.role,
        isActive: user.isActive,
      },
    });
  } catch (error) {
    console.error("Login error:", error instanceof Error ? error.stack : error);
    res.status(500).json({ errors: [{ msg: "Server error occurred. Please try again." }] });
  }
};

const logout = (req: Request, res: Response, next: NextFunction) => {
  try {
    res.clearCookie("jwt", {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict" as const,
    });

    res.status(200).json({ message: "Logout successful" });
  } catch (error) {
    console.error("Logout error:", error instanceof Error ? error.stack : error);
    res.status(500).json({
      errors: [{ msg: "Error during logout process" }]
    });
  }
};

const changePassword = async (
  req: Request & { user?: { _id: string } }, 
  res: Response, 
  next: NextFunction
): Promise<void> => {
    if (!req.user) {
        return next(new AppError("Authentication required", 401));
    }

    const { currentPassword, newPassword } = req.body as { currentPassword?: string; newPassword?: string };
    try {
        const user = await Account.findById(req.user._id);
        if (!user) {
            return next(new AppError("User not found", 404));
        }

        if (!currentPassword || !newPassword) {
            return next(new AppError("Current password and new password are required", 400));
        }

        const isMatch = await bcrypt.compare(currentPassword, user.password);
        if (!isMatch) {
            return next(new AppError("Invalid current password", 400));
        }

        // Check if newPassword is the same as currentPassword
        if (currentPassword === newPassword) {
            return next(new AppError("New password must be different from current password", 400));
        }

        if (newPassword.length < 6) {
            return next(new AppError("New password must be at least 6 characters", 400));
        }

        user.password = await bcrypt.hash(newPassword, 10);
        await user.save();
        console.log("Password changed for:", user.email);
        res.status(200).json({ message: "Password changed successfully" });
    } catch (error) {
        console.error("Password change error:", error instanceof Error ? error.stack : error);
        res.status(400).json({ error: "Password change failed" });
    }
};


const AccountAPI = {
  getAccount,
  getAllAccounts,
  createAccount,
  deleteAccount,
  updateAccount,
  login,
  logout,
  register, 
  changePassword
};
export default AccountAPI;
